services:

  db:
    image: postgres:15
    container_name: churn_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churn_db
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: churn_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: churn_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

volumes:
  postgres_data: